#ifndef UNIDADES_H
#include UNIDADES_H

// AQUI DENTRO DESSE BLOCO VOCÊ COLOCA TODOS OS TIPOS QUE VOCÊ DEFINIR E QUE IRÁ USAR NO PROJETO

// EX:

// STRUCTS;
// PROTÓTIPOS DE FUNÇÕES;
// VARIÁVEIS GLOBAIS
// ...

// QUANDO FOREM CODAR PODE APAGAR ESSES COMENTÁRIOS


#endif  // UNIDADES_H